apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/role: "mongo-role"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-config: "mongodb/creds/mongo-role"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "mongodb/creds/mongo-role" -}}
            export MONGODB_CONNECTION_STRING="mongodb://{{ .Data.username }}:{{ .Data.password }}@mongodb-svc:27017/mydb?tls=false"
          {{- end }}       
      labels:
        app: myapp
    spec:
      serviceAccountName: mydb-sa
      containers:
      - name: app
        image: jweissig/app:0.0.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mydb-sa
  labels:
    app: myapp
