apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynginx
  name: mynginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynginx
  name: mynginx-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mynginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mynginx-ing
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dev.cams7-job.ml
    secretName: dev.cams7-job.ml
  rules:
  - host: dev.cams7-job.ml
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mynginx-svc
            port:
              number: 80
