apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-mongo
  labels:
    app: dynamic-mongo
spec:
  selector:
    matchLabels:
      app: dynamic-mongo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-mongo-role: "mongodb/creds/mongo-role"
        vault.hashicorp.com/agent-inject-template-mongo-role: |
          {
          {{- with secret "mongodb/creds/mongo-role" -}}
            "db_connection": "host=172.31.0.4 port=27017 user={{ .Data.username }} password={{ .Data.password }} dbname=foo tls=false"
          {{- end }}
          }
        vault.hashicorp.com/role: "mongo-role"
      labels:
        app: dynamic-mongo
    spec:
      serviceAccountName: dynamic-mongo
      containers:
      - name: app
        image: jweissig/app:0.0.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamic-mongo
  labels:
    app: dynamic-mongo
