mongodb:
  user: mongouser
  password: mongopwd
  host: mymongo-svc
api:
  image: fabricioveronez/pedelogo-catalogo:1.0.0
  serviceType: ClusterIP  
  ingress:
    enabled: true
    hosts: ["dev.cams7-job.ml"]
