apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
