{{ if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ing
spec:
  ingressClassName: nginx
  tls:
  {{- range .Values.api.ingress.hosts }}
  - hosts:
    - {{ . }}
    secretName: {{ . }}
  {{- end }}
  rules:
  {{- range .Values.api.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ $.Release.Name }}-api-svc
            port:
              number: 80
  {{- end }}
{{ end }}
