apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-api
  name: {{ .Release.Name }}-api-svc
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.api.serviceType }}
