apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-deploy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/role: "mongo-role"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-config: "mongodb/creds/mongo-role"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "mongodb/creds/mongo-role" -}}
            export MONGODB_CONNECTION_STRING="mongodb://{{ .Data.username }}:{{ .Data.password }}@mongodb-svc:27017/mydb?tls=false"
          {{- end }}`}}
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: mydb-sa
      containers:
      - name: api
        image: {{ .Values.api.image }}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: Mongo__User
            value: {{ .Values.mongodb.user }}
          - name: Mongo__Password
            value: {{ .Values.mongodb.password }}
          - name: Mongo__Host
            value: {{ .Values.mongodb.host }}
          - name: Mongo__Database
            value: admin
