apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-mongodb
  name: {{ .Release.Name }}-mongodb-svc
spec:
  selector:
    app: {{ .Release.Name }}-mongodb
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
